version: '3'
services:
  node-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=qazaqunion.kz
      - LETSENCRYPT_HOST=qazaqunion.kz