version: '3'
services:
  node-app:
    restart: always
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - VIRTUAL_HOST=yerezhepova.kz
      - LETSENCRYPT_HOST=yerezhepova.kz